------------------------------------------------------------------------

-- Sample Data Script: A single SQL file providing the scripting to insert sample data into all tables.  
-- The amount of data should be enough to allow adequate testing of an application build upon the designed database.  
-- Rule of Thumb: 20-30 rows per data tables and their associated bridge tables, 
-- and an appropriate number of rows in lookup tables.

------------------------------------------------------------------------

INSERT ALL
    INTO roles VALUES (1,'Administrator')
    INTO roles VALUES (2,'Editors')
    INTO roles VALUES (3,'Users')
    
    INTO users VALUES (1,'Jasper','Camana','jcamana@myseneca.ca','myseneca',1)
    INTO users VALUES (2,'JP','Mendoza','jmendoza@myseneca.ca','myseneca',1)
    INTO users VALUES (3,'Henrique','Sagara','hsagara@myseneca.ca','myseneca',1)  
    INTO users VALUES (4,'Jean','Johann','jjohann@gmail.com','companyaccount',2)
    INTO users VALUES (5,'Warner','Ely','wely@gmail.com','companyaccount',2)
    INTO users VALUES (6,'Biddy','Garrard','bgarrard@gmail.com','companyaccount',2)
    INTO users VALUES (7,'Isabel','Dustin','idustin@gmail.com','companyaccount',2)
    INTO users VALUES (8,'Mason','Street','mstreet@gmail.com','companyaccount',2)
    INTO users VALUES (9,'Doyle','Lawrence','dlawrence@gmail.com','companyaccount',2)
    INTO users VALUES (10,'Serenity','Gilbert','sgilbert@gmail.com','companyaccount',2)
    INTO users VALUES (11,'Gemma','Kellog','gkellog@gmail.com','companyaccount',2)
    INTO users VALUES (12,'Eddy','Cornell','ecornell@gmail.com','companyaccount',2)
    INTO users VALUES (13,'Wenona','Jarett','wjarett@gmail.com','companyaccount',2)
    INTO users VALUES (14,'Greta','Alberts','galberts@gmail.com','useraccount',3)
    INTO users VALUES (15,'Jocelyn','Wilton','jwilton@gmail.com','useraccount',3)    
    INTO users VALUES (16,'Connie','Hunnisett','chunnisett@gmail.com','useraccount',3)    
    INTO users VALUES (17,'Trevor','Gore','tgore@gmail.com','useraccount',3)    
    INTO users VALUES (18,'Anona','Mark','amark@gmail.com','useraccount',3)    
    INTO users VALUES (19,'Hadley','Danniel','hdanniel@gmail.com','useraccount',3)    
    INTO users VALUES (20,'Tessie','Elvis','telvis@gmail.com','useraccount',3)    
    INTO users VALUES (21,'Berny','Langley','blangley@gmail.com','useraccount',3)
    INTO users VALUES (22,'Laura','Lamb','llamb@gmail.com','useraccount',3)
    INTO users VALUES (23,'Bowie','Millard','bmillard@gmail.com','useraccount',3)
    INTO users VALUES (24,'Freeman','Ridge','fridge@gmail.com','useraccount',3)
    INTO users VALUES (25,'Raylene','Carman','rcarman@gmail.com','useraccount',3)
    INTO users VALUES (26,'Braylon','Abrahams','babrahams@gmail.com','useraccount',3)
    INTO users VALUES (27,'Griffin','Godfrey','ggodfrey@gmail.com','useraccount',3)
    INTO users VALUES (28,'Driskoll','Gregory','dgregory@gmail.com','useraccount',3)
    INTO users VALUES (29,'Linnet','Nowell','lnowell@gmail.com','useraccount',3)
    INTO users VALUES (30,'Lianne','Ness','lness@gmail.com','useraccount',3)
    
    INTO privileges VALUES  (1,'Product','Product View',1,1,1,1,1)
    INTO privileges VALUES  (2,'Product','Product View',0,0,0,1,2)
    INTO privileges VALUES  (3,'Prooduct','Product View',1,1,1,1,3)
    INTO privileges VALUES  (4,'Administrator','Admin page',1,0,0,0,2)
    INTO privileges VALUES  (5,'Login','Login Page',1,0,0,0,2)
    INTO privileges VALUES  (6,'Create Post','New Post',1,1,1,1,2)
    INTO privileges VALUES  (7,'Administrator','Admin page',1,1,1,1,1)
    INTO privileges VALUES  (8,'Login','Login page',1,1,1,1,1)
    INTO privileges VALUES  (9,'Create Post','New Post',1,1,1,1,1)
    INTO privileges VALUES  (10,'Comments','Create Comments',1,1,1,1,3)
    INTO privileges VALUES  (11,'Comments','Create Comments',1,1,1,1,2)
    INTO privileges VALUES  (12,'Comments','Create Comments',1,1,1,1,1)
    INTO privileges VALUES  (13,'Contact Us','Contact page',1,1,1,1,1)
    INTO privileges VALUES  (14,'Contact Us','Contact page',1,1,1,1,2)
    INTO privileges VALUES  (15,'Contact Us','Contact page',0,0,0,1,3)
    INTO privileges VALUES  (16,'Product - Laptops','Laptop Page',1,1,1,1,1)
    INTO privileges VALUES  (17,'Product - Laptops','Laptop Page',0,0,0,1,2)
    INTO privileges VALUES  (18,'Product - Laptops','Laptop Page',0,0,0,1,3)
    INTO privileges VALUES  (19,'Product - Video Games','Video Games',1,1,1,1,1)
    INTO privileges VALUES  (20,'Product - Video Games','Video Games',0,0,0,0,2)
    INTO privileges VALUES  (21,'Product - Video Games','Video Games',0,0,0,0,3)
    
    INTO categories VALUES (1, 'Laptops', 'Battery- or AC-powered personal computer generally smaller than a briefcase that can easy be transported and conveniently used in temporary spaces such as on airplanes')
    INTO categories VALUES (2, 'Video Games', 'Electronic game that can be interacted with using an input device, such as a controller, keyboard, or joystick')
    INTO categories VALUES (4, 'Mice', 'A computer mouse is a handheld hardware input device that controls a cursor in a GUI (graphical user interface) for pointing, moving and selecting text, icons, files, and folders on your computer. ')
    INTO categories VALUES (5, 'Keyboards', 'Modern computer keyboards were modeled after, and are still very similar to, classic typewriter keyboards.')
    INTO categories VALUES (6, 'Monitors', 'A monitor is an electronic output system which is referred to as a Video Display (VDT) or video display (VDU) unit.')
    INTO categories VALUES (7, 'Graphics Cards', 'Graphics card is also known as video card. It’s an expansion card plugged into your computer that handles what your computer displays on your computer screen.')
    INTO categories VALUES (8, 'Drone Accessories', 'Drone accessories are an often overlooked yet important aspect of the drone flight experience. Accessories like a carrying case, SD cards, extra batteries and propellers, and ND filters will help you get the most out of your drone both in performance and lifespan.')
    
    INTO products VALUES (1, 'Marvel''s Spider-Man 2', 'Sony Interactive Entertainment', 'video game', 1, 4, 2)
    INTO products VALUES (2, 'EA Sports Fifa 23', 'EA Sports', 'video game', 1, 11, 2)
    INTO products VALUES (3, 'Super Smash Bros Ultimate', 'Nintendo', 'video game', 1, 5, 2)
    INTO products VALUES (4, 'Super Mario Odyssey', 'Nintendo', 'video game', 1, 8, 2)
    INTO products VALUES (5, 'Halo Infinite', 'Xbox Game Studios', 'video game', 1, 9, 2)
    INTO products VALUES (6, 'Grand Theft Auto V', 'Rockstar Games', 'video game', 1, 10, 2)
    INTO products VALUES (7, 'MSI GF63 Thin 10SC', 'MSI', 'Laptop', 1, 9, 1)
    INTO products VALUES (8, 'Asus VivoBook R 15.6" TouchCore i5-1135G7 Iris Xe', 'Asus', 'Laptop', 1, 9, 1)
    INTO products VALUES (9, 'MSI Katana GF66 Gaming', 'Asus', 'Laptop', 1, 9, 1)
    INTO products VALUES (10, 'ASUS ROG Strix G17', 'Asus', 'Laptop', 1, 11, 1)
    INTO products VALUES (11, 'Lenovo IdeaPad 5i', 'Lenovo', 'Laptop', 1, 4, 1)
    INTO products VALUES (12, 'HP15-ef2030ca Notebook', 'HP', 'Laptop', 1, 10, 1)
    INTO products VALUES (13, 'Acer TravelMate', 'Acer', 'Laptop', 1, 13, 1)
    INTO products VALUES (14, 'Huawei Matebook 14"', 'Huawei', 'Laptop', 1, 13, 1)
    INTO products VALUES (15, 'HP 15Z-EF2000 15.6"', 'HP', 'Laptop', 1, 6, 1)
    INTO products VALUES (16, 'DJI Tello Boost Combo', 'DJI', 'Drone Accessories', 1, 4, 8)
    INTO products VALUES (17, 'DJI Tello Battery', 'DJI', 'Drone Accessories', 1, 8, 8)
    INTO products VALUES (18, 'Gigabyte Radeon RX 6650XT', 'Gigabyte', 'Graphics Card', 1, 9, 7)
    INTO products VALUES (19, 'Gigabyte GeForce RTX 3070 Gaming', 'Gigabyte', 'Graphics Card', 1, 7, 7)
    INTO products VALUES (20, 'ASUS ROG Strix GeForce RTX 4090 Gaming', 'Asus', 'Graphics Card', 1, 4, 7)
    INTO products VALUES (21, 'EVGA GeForce RTX 3060 XC Gaming', 'EVGA', 'Graphics Card', 1, 8, 7)
    INTO products VALUES (22, 'Logitech MK270 Wireless Desktop Combo', 'Logitech', 'Keyboard', 1, 6, 5)
    INTO products VALUES (23, 'Logitech G502 HERO Gaming Mouse', 'Logitech', 'Mouse', 1, 11, 4)
    INTO products VALUES (24, 'Redragon KUMARA RGB Led Mechanical Gaming Keyboard', 'Redragon', 'Keyboard', 1, 12, 5)
    INTO products VALUES (25, 'Corsair K55 RGB PRO Gaming Bundle', 'Corsair', 'Keyboard', 1, 11, 5)
    INTO products VALUES (26, 'Microsoft Wireless mobile mouse 1850 - Black', 'Microsoft', 'Mouse', 1, 6, 4)
    INTO products VALUES (27, 'iCAN K-918', 'iCan', 'Keyboard', 1, 7, 5)
    INTO products VALUES (28, 'Gigabyte G27F 2 27" Gaming Monitor IPS', 'Gigabyte', 'Monitor', 1, 12, 6)
    INTO products VALUES (29, 'Asus VZ24EHE 23.8" Full HD Monitor IPS', 'Asus', 'Monitor', 1, 8, 6)
    INTO products VALUES (30, 'Philips Momentum 329M1RV 32" 4k IPS', 'Philips', 'Monitor', 1, 7, 6)
    INTO products VALUES (31, 'Samsung 24" Monitor FHD', 'Samsung', 'Monitor', 1, 9, 6)
    
    INTO comments VALUES (1, 1, 4, 1, 4.5, 'sample comment')
    INTO comments VALUES (2, 4, 4, 1, 3.9, 'sample comment')
    INTO comments VALUES (3, 6, 4, 1, 2.8, 'sample comment')
    INTO comments VALUES (4, 31, 8, 1, 2.6, 'sample comment')
    INTO comments VALUES (5, 6, 30, 1, 3.4, 'sample comment')
    INTO comments VALUES (6, 28, 21, 1, 4.7, 'sample comment')
    INTO comments VALUES (7, 27, 7, 1, 3.9, 'sample comment')
    INTO comments VALUES (8, 7, 7, 1, 2.9, 'sample comment')
    INTO comments VALUES (9, 17, 29, 1, 2.6, 'sample comment')
    INTO comments VALUES (10, 7, 2, 1, 2.5, 'sample comment')
    INTO comments VALUES (11, 12, 26, 1, 3.4, 'sample comment')
    INTO comments VALUES (12, 6, 3, 1, 2.3, 'sample comment')
    INTO comments VALUES (13, 6, 8, 1, 4.3, 'sample comment')
    INTO comments VALUES (14, 30, 17, 1, 4.9, 'sample comment')
    INTO comments VALUES (15, 2, 28, 1, 2.3, 'sample comment')
    INTO comments VALUES (16, 3, 22, 1, 3.2, 'sample comment')
    INTO comments VALUES (17, 6, 30, 1, 4.9, 'sample comment')
    INTO comments VALUES (18, 8, 23, 1, 4.4, 'sample comment')
    INTO comments VALUES (19, 20, 7, 1, 2.3, 'sample comment')
    INTO comments VALUES (20, 22, 15, 1, 2.5, 'sample comment')
    INTO comments VALUES (21, 19, 3, 1, 2.2, 'sample comment')
    INTO comments VALUES (22, 18, 18, 1, 4.2, 'sample comment')
    INTO comments VALUES (23, 23, 25, 1, 3.3, 'sample comment')
    INTO comments VALUES (24, 21, 30, 1, 2.3, 'sample comment')
    INTO comments VALUES (25, 18, 24, 1, 2, 'sample comment')
    INTO comments VALUES (26, 16, 25, 1, 3.6, 'sample comment')
    INTO comments VALUES (27, 17, 4, 1, 3.8, 'sample comment')
    INTO comments VALUES (28, 13, 2, 1, 3.9, 'sample comment')
    INTO comments VALUES (29, 28, 19, 1, 3.8, 'sample comment')
    INTO comments VALUES (30, 30, 3, 1, 3.8, 'sample comment')
    INTO comments VALUES (31, 16, 19, 1, 4.3, 'sample comment')
    INTO comments VALUES (32, 27, 2, 1, 3.2, 'sample comment')
    INTO comments VALUES (33, 28, 28, 1, 4.4, 'sample comment')
    INTO comments VALUES (34, 14, 16, 1, 5, 'sample comment')
    INTO comments VALUES (35, 20, 5, 1, 3, 'sample comment')
    INTO comments VALUES (36, 7, 10, 1, 4.8, 'sample comment')
    INTO comments VALUES (37, 24, 26, 1, 2.9, 'sample comment')
    INTO comments VALUES (38, 29, 28, 1, 2.3, 'sample comment')
    INTO comments VALUES (39, 1, 27, 1, 2.6, 'sample comment')
    INTO comments VALUES (40, 11, 26, 1, 3.8, 'sample comment')
    INTO comments VALUES (41, 18, 25, 1, 4.4, 'sample comment')
    INTO comments VALUES (42, 27, 26, 1, 3, 'sample comment')
    INTO comments VALUES (43, 10, 16, 1, 3.6, 'sample comment')
    INTO comments VALUES (44, 13, 21, 1, 3.4, 'sample comment')
    INTO comments VALUES (45, 25, 26, 1, 3.2, 'sample comment')
    INTO comments VALUES (46, 28, 25, 1, 3.3, 'sample comment')
    INTO comments VALUES (47, 17, 12, 1, 4.1, 'sample comment')
    INTO comments VALUES (48, 26, 10, 1, 3.6, 'sample comment')
    INTO comments VALUES (49, 23, 16, 1, 4.8, 'sample comment')
    INTO comments VALUES (50, 30, 2, 1, 2.1, 'sample comment')
    INTO comments VALUES (51, 9, 16, 1, 2.6, 'sample comment')
    INTO comments VALUES (52, 20, 17, 1, 2.7, 'sample comment')
    INTO comments VALUES (53, 26, 17, 1, 4.5, 'sample comment')
    INTO comments VALUES (54, 10, 2, 1, 3.3, 'sample comment')
    INTO comments VALUES (55, 11, 13, 1, 4.9, 'sample comment')
    INTO comments VALUES (56, 31, 12, 1, 3.4, 'sample comment')
    INTO comments VALUES (57, 29, 25, 1, 2, 'sample comment')
    INTO comments VALUES (58, 21, 4, 1, 3.5, 'sample comment')
    INTO comments VALUES (59, 16, 7, 1, 3.8, 'sample comment')
    INTO comments VALUES (60, 27, 24, 1, 3.9, 'sample comment')
SELECT * FROM dual;
